language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh 3.0.x

script:
  - phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=coverage.clover

notifications:
slack: jiangbianwanghai:SklSZHKIP7EvIle7q8Nb5My0
